### PR TITLE
Update Community Resources for Sweden

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by bhousel** [comment]
Can we keep an email address there that will go to a person in the community?

**Comment by magol** [comment]
@bhousel I actually do not really know who it could be. It is no official contact person for the Swedish OSM community, that I know about.

The maintainer of https://github.com/joakimfors/openstreetmap.se-content is @joakimfors. Maybe he is the right person to answer that question. 

In any case, the e-mail address that is used now is completely wrong. Firstly, I'm not particularly active in the community; secondly, that email address is inactive (where did you found that adress).

Sorry I misunderstood the purpose of "Points of contact" when I created #87. I thought it was just about who you could talk to about the information, not that I become a public contact person.

**Comment by bhousel** [comment]
> In any case, the e-mail address that is used now is completely wrong. Firstly, I'm not particularly active in the community; secondly, that email address is inactive (where did you found that adress).

Oh sorry!  When I'm looking for an OSM persons email I just Google "<persons name> site:lists.openstreetmap.org"

> Sorry I misunderstood the purpose of "Points of contact" when I created #87. I thought it was just about who you could talk to about the information, not that I become a public contact person.

It's not really for a public contact person - It's more for things like if the website or Facegroup group or whatever returns a 404, I would email to ask them if we should replace it with something else.  Many of the groups have a shared account like "team@openstreetmap.se" and that's fine.

**Comment by magol** [comment]
> Oh sorry! When I'm looking for an OSM persons email I just Google "person's name site:lists.openstreetmap.org"

Ahh, now I learned something new  :-)

> It's not really for a public contact person - It's more for things like if the website or Facegroup group or whatever returns a 404, I would email to ask them if we should replace it with something else. Many of the groups have a shared account like "team@openstreetmap.se" and that's fine.

I have asked in the mail group if it is shared account to mail to, but I have not received any answer.
On openstreetmap.se, it is stated that you should contact talk-se or #osm.se @ irc.oftc.net if you want to contact the administrator.

So I suppose talk-se is the best option right now.

**Comment by bhousel** [comment]
> I have asked in the mail group if it is shared account to mail to, but I have not received any answer.
> On openstreetmap.se, it is stated that you should contact talk-se or #osm.se @ irc.oftc.net if you want to contact the administrator.
> 
> So I suppose talk-se is the best option right now.

ok, I noticed on the listinfo page that each mailing list does have an owner account, so I'll just use that:

screenshot 2018-04-21 18 36 50

**Pull request merged**
