### PR TITLE
Added OSM world Matrix community

### LINKED ISSUE #305: OSM World Matrix community
## Community Resource Name

OpenStreetMap World Matrix Community

### What is it?

A community built on Matrix, a decentralised chat ecosystem. The rooms are also bridged with the OSM World Discord.

### URL link to the resource

Community link: https://matrix.to/#/+osmworld:privacytools.io

Main room link: https://matrix.to/#/!oDhjtNSpfTCAUmKBwW:privacytools.io?via=privacytools.io&via=t2bot.io&via=matrix.org

### Points of contact

Not sure if understood, but I guess it means the contact to the admin.

It's @megaarthur:privacytools.io on Matrix or
minecrartek [at] protonmail.com

### Bounding polygon

Worldwide

### PR DESCRIPTION
**Pull request by MegaArthur**
Closes #305

### CODE REVIEW

**Comment by bhousel** [comment]
@harry-wood is this ok with the CWG?
We'd be showing this resource to all OSM users worldwide.

**Comment by ValorNaram** [comment]
CWG is not involved in such things: community souvernenity.

**Comment by iandees** [comment]
What is `+osmworld:privacytools.io`?

**Comment by bhousel** [comment]
> CWG is not involved in such things: community souvernenity.

**Comment by MegaArthur** [comment]
@iandees This is a Matrix community address, pointing to OSM World rooms

**Comment by iandees** [comment]
How is `privacytools.io` related to OSM?

**Comment by MegaArthur** [comment]
It's just a matrix homeserver, like matrix.org.

**Comment by MegaArthur** [comment]
@bhousel If this helps, the Matrix rooms are bridged with the OSM World Discord and I cooperate with the staff there in managing the rooms

**Comment by bhousel** [comment]
I've thought about it more and I think I'm just going to close this for now.. It sounds sketchy and came from someone not using their real name.  

If the OSMF or CWG wants to set up a global Matrix chat (or even if someone stopped by to say "sure we are ok with it"), I'm happy to add it to this index, but I'm not comfortable accepting a pull request like this that would show this chatroom to all the OSM users everywhere.

**Comment by ValorNaram** [comment]
> doesn’t come from someone directly involved in the organization it is for.

Emmm a community member does not need to be involved into the OSMF in order to create a communication channel for the OpenStreetMap Community. OSMF is not controlling this project, it's supporting it and gives it a face for the public if needed.

**Comment by MegaArthur** [comment]
> and came from someone not using their real name

Don't really see a point in using my real name here, I can ask someone from the OSM World Discord administration to msg you is you want

**Comment by ValorNaram** [comment]
> Don't really see a point in using my real name here,

1. The internet allows anomymisation but it's designed for communication and collaboration and therefore it helps to use real name instead of pseudonym.
2. It puts others in a more comfortable way to trust your work.

**Comment by harrija0** [comment]
Hi, @bhousel.  I am the mod for OSM World Discord and approve adding of the matrix bridge to the community index.  We have had some discussion on our side about users and, unfortunately, vandalism.  We had posts from two matrix users that we terminated and it sparked discussion about the bridge.  Recently we removed the OSM discord listing from the matrix index.  I think this will minimize random trolling while enabling those who wish to use a link through Matrix to join the discussion.  From now on members will only learn about the matrix bridge from our Discord or the OSM Community Index.

Thanks for the discussion and protection of our platform.  I welcome more comments if there are concerns.
-Austin/Zandu

**Comment by danieldegroot2** [comment]
Just fyi, the url has since changed to Spaces: https://matrix.to/#/#osmworld:matrix.org (and instead of `url`, use `account`: `#osmworld`).

_See also: #514, #524 ._

**Pull request closed without merging**
