### PR TITLE
Add Catalan Countries Community

### PR DESCRIPTION
**Pull request by jmaspons**

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @jmaspons  & welcome 👋

**Comment by bhousel** [comment]
@jmaspons I took a look at `catalan_countries.geojson` and it's pretty detailed..
For comparison:
```
Size      File                             
--------  ---------------------------------
14.02 KB  catalan_countries.geojson        
12.99 KB  india_andhrapradesh.geojson      
12.74 KB  india_telengana.geojson          
 7.42 KB  india_maharashtra.geojson        
 6.06 KB  india_karnataka.geojson          
  5.7 KB  india_kerala.geojson             
 5.48 KB  ukraine.geojson                  
  4.3 KB  lazio.geojson                    
 3.88 KB  bahia.geojson                    
 3.71 KB  india_tamilnadu.geojson          
 3.28 KB  wallonia.geojson                 
 2.75 KB  galicia.geojson                  
  2.2 KB  flanders.geojson                 
```

I'd like to reduce the precision of it by a lot.   Any objections?

The purpose of this boundary is not to be legally strict, but rather to just point people at e.g. a Facebook or Telegram channel that they might find interesting.  It can be really rough.

**Comment by jmaspons** [comment]
Yes, no problem. I did some tests simplifying the feature and have 9 KiB version at hand. Tell me if it's OK or should I reduce a little more.

Do you know when the strings will appear on transifex?

**Comment by bhousel** [comment]
> Yes, no problem. I did some tests simplifying the feature and have 9 KiB version at hand. Tell me if it's OK or should I reduce a little more.

It's not that we are looking for a specific number, but rather just the smallest thing that works.  

Size-wise, this...
Screen Shot 2020-11-17 at 10 16 29 AM

.. is way better than this:
Screen Shot 2020-11-17 at 10 16 45 AM

**Comment by jmaspons** [comment]
No problem from my side, go ahead. I hope no Spanish get annoyed for some unexpected links to the catalan comunity

**Comment by bhousel** [comment]
Ok, I've simplified it down to 250 bytes in de7ade4

**Pull request merged**
