### PR TITLE
Updated for Colombia

### PR DESCRIPTION
**Pull request by angoca**
Several social networked included, contacts, and other elements for Colombia and Bogota

### CODE REVIEW

**Comment by angoca** [comment]
Could you help me integrating this pull request?

**Comment by bhousel** [comment]
Thanks @angoca 👍

**Comment by eisams** [comment]
Thanks for updating this!
Some feedback after having looked at [community pages across the world](https://community.openstreetmap.org/t/add-all-community-forums-to-the-community-index/119315):
Should the github account be the number one spot?
I'd think that's a bit specific for new users @angoca 

I would also put the community forum above the talk-co mailing list, that mostly has "spam" from the weekly OSM team?
And consider if it should be in spot 1?

**Comment by angoca** [comment]
I didn't know this needed to be modified. When I created the files, I thought they were sorted alphabetically.
Is that the purpose of the `order` parameter?

**Comment by eisams** [comment]
If no `order` parameter is specified it is alphabetical
Higher values get prioritized, and negative values penalized (i.e., no order parameter is implicity order=0)

You can see it here: https://openstreetmap.community/?map=2.81421,-72.32789&zoom=3.87

**Comment by angoca** [comment]
Thank you for the explanation. I created a new pull request with the changes.

**Pull request merged**
