### PR TITLE
add talk-us mailing list

### LINKED ISSUE #218: Add talk-us mailing list to the USA entry
## Community Resource Name

"OpenStreetMap US Mailing List"

### What is it?

mailing list

### URL link to the resource

https://lists.openstreetmap.org/listinfo/talk-us

### Points of contact

no idea

### Bounding polygon

not needed, just add it to https://github.com/osmlab/osm-community-index/blob/master/resources/north-america/united_states/OSM-US.json

### Languages spoken (optional)

"en"

### Country codes (optional)

"us"

### Add an emoji flag (optional)

no emoji, please

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #218

### CODE REVIEW

**Comment by matkoniecz** [comment]
`npm run test` fails with

```
  /home/mateusz/Desktop/tmp/osm-community-index/resources/north-america/united_states/talk-us-mailing-list.json: 
  instance requires property "contacts"
```

but I have no idea who should be listed as contacts

**Comment by bhousel** [comment]
We are more recommending people join the Slack instead, and the mailing list isn’t used much anymore.

**Comment by matkoniecz** [comment]
Slack? Is it available to general public?

https://osmus.slack.com/signup shows me 

selection_002

**Comment by matkoniecz** [comment]
And "Contact your Workspace Administrator for an invitation." is not a link.

**Pull request closed without merging**
