### PR TITLE
Add resources for Poland

### PR DESCRIPTION
**Pull request by RicoElectrico**
I added a few resources for Poland: forum, FB group and mailing list. They all get read by quite considerable amount of people.

Could also add Discord, but I would need to know which type to use (and get admin's contact info).

How could I add #openstreetmap tag on Wykop.pl ( https://www.wykop.pl/tag/openstreetmap/ )? One can ask for help on the microblog as well - 46 users watch the tag.

### CODE REVIEW

**Comment by gscscnd** [comment]
What about `#osm-pl` channel?

**Comment by bhousel** [comment]
Looks good, thanks!

> Could also add Discord, but I would need to know which type to use (and get admin's contact info).

Oh interesting - I did not realize ["Discord"](https://discordapp.com/) and ["Discourse"](https://www.discourse.org/) were two different things. 😆 

If Discord is popular and used, we can add a type for it.  (please add a comment on #49 if you want this)

> How could I add #openstreetmap tag on Wykop.pl ( https://www.wykop.pl/tag/openstreetmap/ )? One can ask for help on the microblog as well - 46 users watch the tag.

You can add a .json for this resource and use either type "group" or "forum".  It looks more like a "forum" to me.

> What about #osm-pl channel?

Sure, if people are using it.  (for example see [OSM-AR-irc.json](https://github.com/osmlab/osm-community-index/blob/master/resources/south-america/argentina/OSM-AR-irc.json) )

(I will wait to merge until you say it's 🆗 )

**Comment by matkoniecz** [comment]
> OSM-PL-mailinglist

It is dead, is there a point in linking it? See https://lists.openstreetmap.org/pipermail/talk-pl/

In Poland nearly 100% of discussion is on forum with some limited discussion in changeset discussions.

**Comment by bhousel** [comment]
> It is dead, is there a point in linking it? See https://lists.openstreetmap.org/pipermail/talk-pl/
> 
> In Poland nearly 100% of discussion is on forum with some limited discussion in changeset discussions.

This is good info, thanks @matkoniecz -  
Yeah if the mailing list or irc is not active, please do not include them.

**Comment by matkoniecz** [comment]
@RicoElectrico Are you planning on updating this PR?

**Comment by bhousel** [comment]
This has been sitting a while and it actually looks fine, so I just merged it... 
If you want any changes after it goes live - let me know!

**Comment by matkoniecz** [comment]
> OSM-PL-mailinglist

It is dead, is there a point in linking it? See https://lists.openstreetmap.org/pipermail/talk-pl/

In Poland nearly 100% of discussion is on forum with some limited discussion in changeset discussions.

I opened #93 covering this.

**Pull request merged**
