### PR TITLE
Added Latvian OSM Discord and Signal links

### PR DESCRIPTION
**Pull request by XeMoPHOs**

### CODE REVIEW

**Comment by bhousel** [comment]
We don't actually support `signal` yet as a resource type. How does it work in this case, kind of like a group like telegram?

**Comment by richlv** [comment]
The group link is https://signal.group/#CjQKIBQDZFRYENhgTzY0czaSnYxt6-NCXdW5Rp2o6144bO4wEhCUSXKPmsjKnTbzUgLj0MpL .

**Comment by i-ky** [comment]
@XeMoPHOs, could you please add https://osmlatvija.zulipchat.com/ as well?

**Comment by XeMoPHOs** [comment]
Added zulip aswell, but is that a valid resource type?

**Comment by i-ky** [comment]
> Added zulip aswell, but is that a valid resource type?

Seems it isn't:
https://github.com/osmlab/osm-community-index/blob/95d6b0966f1449d121699dcff49a4f2d73be20ba/schema/resource.json#L21-L53

**Comment by XeMoPHOs** [comment]
@bhousel Could you add Zulip as a resource too, just so there isn't a misunderstanding?

**Comment by richlv** [comment]
> May I ask - why does the Latvian community use so many different chat apps? Why not just pick one so that everyone is on the same thing?

It's a relatively large community for a small region, and there are diverse communication preferences.
Still, the fragmentation is not desirable, and a satisfying solution is being sought. Zulip marks a lot of checkboxes, and we started testing it very recently. It seems to be a very decent solution, and might replace majority of other channels - but that remains to be seen.

**Comment by richlv** [comment]
Regarding the commit - I suppose the Zulip URL might need the protocol prefix, https:// ?
Currently the URL on https://openstreetmap.community/ is https://openstreetmap.community/osmlatvija.zulipchat.com .

**Pull request merged**
