### PR TITLE
Add Lithuanian mailing list and forum

### PR DESCRIPTION
**Pull request by eginhard**

### CODE REVIEW

**Comment by empersOSM** [comment]
Mailing list
https://lists.openstreetmap.org/listinfo/talk-lt
IRC
irc://irc.oftc.net #osm-lt
Lithuanian OSM Community website
www.openstreetmap.lt
Forum
https://forum.openstreetmap.org/viewforum.php?id=96

**Comment by bhousel** [comment]
Thanks @eginhard 👍

**Comment by eginhard** [comment]
Thanks @empersOSM! Is the IRC still active? It was empty the two times I checked.

**Comment by empersOSM** [comment]
I believe it is not anymore.

**Comment by eginhard** [comment]
Ok, thanks! Then it's fine like this, they are shown now on https://openstreetmap.community/

**Pull request merged**
