### PR TITLE
Add community links for Germany.

### PR DESCRIPTION
**Pull request by hikemaniac**
This PR adds several community links for Germany (website, forum, mailinglist, IRC). 

The germany.geojson is quite large, because I extracted the coordinates from the Germany polygon on OpenStreetMap. If it's needed, I can simplify the geometry. Another issue is the contact e-mail address. I didn't really find anything proper on the openstreetmap.de website so I chose Frederik Ramms (@woodpeck) e-mail, which I found on the mailinglist page as contact information. Is that okay for you?

### CODE REVIEW

**Comment by bhousel** [comment]
> The germany.geojson is quite large, because I extracted the coordinates from the Germany polygon on OpenStreetMap. If it's needed, I can simplify the geometry.

Yes, you'll definitely need to simplify it..  Try to get it down to around 10 kb or less.. It doesn't need to be very accurate.

You can do `npm run stats` to see the sizes of everything (Belgium could benefit from simplification too)

> Another issue is the contact e-mail address. I didn't really find anything proper on the openstreetmap.de website so I chose Frederik Ramms (@woodpeck) e-mail, which I found on the mailinglist page as contact information. Is that okay for you?

Sure if @woodpeck is ok with it.

**Comment by hikemaniac** [comment]
I ended up with a rough hand-drawn version of the `germany.geojson`-file. It's only 16 kb large, but also not very precise. I hope it's okay now.

By the way, is there a `type` for the Germany OSM Blog? They have really nice weekly reports of what's happening on OSM and I think this is definitely a great way to engage the community.

**Comment by bhousel** [comment]
> I ended up with a rough hand-drawn version of the germany.geojson-file. It's only 16 kb large, but also not very precise. I hope it's okay now.

Looks great!

> By the way, is there a type for the Germany OSM Blog? They have really nice weekly reports of what's happening on OSM and I think this is definitely a great way to engage the community.

I've been using the type "group" for anything like a local chapter or user group with a blog or website. 
In fact I added `openstreetmap.at` as a "group" too: [osm-at.json](https://github.com/osmlab/osm-community-index/blob/master/resources/europe/at/osm-at.json)

example rendering of the OSM-US group:

screenshot 2018-04-07 15 00 56 copy

**Comment by hikemaniac** [comment]
Great, thanks. 😊 I just added the blog.

**Comment by bhousel** [comment]
> Great, thanks. 😊 I just added the blog.

oh I just looked - it doesn't make sense to have links to both `blog.openstreetmap.de` and `www.openstreetmap.de` - they are 2 things on the same site. I'm going to remove the blog file and merge..

**Comment by bhousel** [comment]
I did a squash-merge on the command line, thanks @hikemaniac!

**Comment by mmd-osm** [comment]
IRC links to a website using Java applets. This is pretty much of no use at all in 2018.

**Comment by bhousel** [comment]
> (The other question is if anyone still wants to use IRC in 2018).

My gut says that links to resources like IRC and mailing lists do more harm than good.  At least in the US, these things make the OSM project look very geeky.  My worry is that people will see that and think _"this OSM stuff isn't for me"_ and the message I'm trying to convey with this screen is _"lots of people around you care about OSM"_.  

However I also don't know what the convention is in other parts of the world, so I'm letting each local group decide for themselves what they want this screen to show.  Many groups use Riot chat now, with a bridge to their IRC channel.

**Pull request closed without merging**
