### PR TITLE
Add 4 Indian XMPP communities

### PR DESCRIPTION
**Pull request by contrapunctus-1**

### CODE REVIEW

**Comment by bhousel** [comment]
Why make a second India matrix ?  Wouldnt this confuse people?

**Comment by contrapunctus-1** [comment]
@bhousel The first one is bridged to Telegram, whereas the newer one is not bridged to any proprietary network services.

**Comment by bhousel** [comment]
@contrapunctus-1 why do you care?  

Starting a fight over what Matrix can bridge to what other resources has got to be one of the most pointless things I've ever heard of.  It would be messed up to expect us to show users a list of resources that includes both the Telegram and the 2 Matrixes that either do or don't bridge to it.

**Comment by contrapunctus-1** [comment]
It's because at least part of the community cares about its privacy, and thus wishes to avoid proprietary network services.

That said, I recognize the potential UX issues, so I've removed the second Matrix room.

**Comment by bhousel** [comment]
Thanks @contrapunctus-1

**Pull request merged**
