### PR TITLE
Add community links for Italy.

### PR DESCRIPTION
**Pull request by hikemaniac**
In addition to the few currently available regional resources for Italy, this PR adds Italy-wide community links. Could you please do the building, to simplify the Italy polygon?
I used @dieterdreist as contact address, because he set himself as a contact for the Lazio region. @dieterdreist is that okay for you?

### CODE REVIEW

**Comment by RobJN** [comment]
If you want a different contact then maybe try @AleZena from the OSMF Local Chapter for Italy. Also is it worth adding OSMF's State of the Map 2018 here given that it is hosted in Italy, or should that go elsewhere?

**Comment by dieterdreist** [comment]
yes, I believe AleZena is a much better contact address for Italy as a whole, although generally I am not sure whether we need national community contacts, local contacts are usually much more relevant 
to mappers

**Comment by sabas** [comment]
For talk-it I'm currently the mailing list administrator.
There are also the social channels https://www.facebook.com/OpenStreetMap.Italia/ | https://twitter.com/OpenStreetMapIt

Local / topical mailing lists need to be added?

**Comment by bhousel** [comment]
Thanks everyone, I removed the forum since it is not used, added Facebook and Twitter, and updated the contacts for the Italian resources..

**Comment by bhousel** [comment]
> Also is it worth adding OSMF's State of the Map 2018 here given that it is hosted in Italy, or should that go elsewhere?

Good suggestion @RobJN 
I actually think we should add https://blog.openstreetmap.org/ as a global resource, and attach the SOTM event there.. (I'll do this now)

**Pull request merged**
