### PR TITLE
Nobody should be sent to the Discord server

### PR DESCRIPTION
**Pull request by simonpoole**
See https://lists.openstreetmap.org/pipermail/talk/2021-March/086291.html

### CODE REVIEW

**Comment by tastrax** [comment]
I am not sure this is a wise move as the discord channel provides a valuable and convenient service to many people. There are far worse instances of 'issues' on the mailing lists but they are still prominent within the lists

**Comment by simonpoole** [comment]
> 
> 
> I am not sure this is a wise move as the discord channel provides a valuable and convenient service to many people. There are far worse instances of 'issues' on the mailing lists but they are still prominent within the lists

Removing the marketing for the server does not impact people using it. 

As to the bogey man "mailing lists" we're all humans, busy communication channels with lots of participants are going to have an increased probability for incidents, given that, the number on the larger mailing lists is minimal, and those can be scrutinized by all without being forced to sign up to a service with unknown operators.

**Comment by matkoniecz** [comment]
Have you visited that Discord server? Or seen any content claimed to be present there by that person? Because the description posted there seems extremely inaccurate to me (pinging @bhousel who may be able to confirm/deny that)

**Comment by tastrax** [comment]
The individual has been in private discussions with several people by the looks of it.

image

**Comment by matkoniecz** [comment]
Full response is posted at https://lists.openstreetmap.org/pipermail/talk/2021-March/086297.html

**Comment by bhousel** [comment]
It sounds like mods are looking into the issue.  I agree that the "world" resources should be held to a higher standard than the local ones, but it's premature to just remove it from the community-index because one person is mad.  Let them work through whatever process they have for dealing with trolls.

**Pull request closed without merging**
