### PR TITLE
Create osm-iraq-mailing-list

### PR DESCRIPTION
**Pull request by lukaszkruk**
adding the first iraq community

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @lukaszkruk, and welcome 👋

**Comment by lukaszkruk** [comment]
Thanks @bhousel :)

I just made a tiny OSM edit with iD in Iraq hoping that the community added through this PR would pop up on the left-hand pane, but it does not. Should it be there, or am I missing something? Or was it simply not enough time for this to get included in iD?

Cheers!

image

**Comment by bhousel** [comment]
> Should it be there, or am I missing something? Or was it simply not enough time for this to get included in iD?

I don't know.. I included it in v2.1.2, so they should have it 🤷

**Comment by bhousel** [comment]
Just looked into it and the reason this never got brought in was because there's no .json extension on the file, so it was skipped.
I renamed the file in ff8e5a8

**Comment by lukaszkruk** [comment]
Oops, thanks for the fix!

**Comment by bhousel** [comment]
> Oops, thanks for the fix!

No worries @lukaszkruk , there were a few other files like this too.. 
In 8d20f54 I added a check so we can catch if it happens again.

**Pull request merged**
