### PR TITLE
Adding Matrix Kosovo group

### PR DESCRIPTION
**Pull request by ValorNaram**
Hey,

this PR contains the necessary files to add the Matrix Channel "OpenStreetMap Kosovo". The Telegram and the Matrix ones are connected, so you can interact with the one on Telegram by joining the one in Matrix and vis versa.

### CODE REVIEW

**Comment by bhousel** [comment]
Sure we can add this - few questions though:
1. Do you definitely want to have separate entries for Telegram and Matrix separate if they are bridged?
2. Is @grischard  definitely the right contact for this?  Is that really his email? 

(Sometimes we've seen people request stuff added based on a thing they found on the OSM Wiki, and I'd prefer for this community index to be more driven by the communities themselves - like someone from Kosovo should be making this request).

**Comment by ValorNaram** [comment]
> Is @grischard definitely the right contact for this? Is that really his email?

He is just the right one for the one in Telegram.

> Do you definitely want to have separate entries for Telegram and Matrix separate if they are bridged?

Yes because Matrix users who do not use Telegram need to know how to access the group via Matrix. It has another url and the circumstances of joining are also different. As Matrix user you cannot use the t.me link from Telegram to join this group from inside Matrix.

**Comment by ValorNaram** [comment]
> (Sometimes we've seen people request stuff added based on a thing they found on the OSM Wiki, and I'd prefer for this community index to be more driven by the communities themselves - like someone from Kosovo should be making this request).

I'm one of the moderators of the one in Telegram and I've also made the bridge to Matrix. The bridge has been discussed within the community on Telegram because we had to add a bot in our Telegram group that links the group on Telegram with the one in Matrix.

**Comment by bhousel** [comment]
Ok thanks for confirming @ValorNaram & welcome 👋

**Pull request merged**
