### PR TITLE
Adjust the northern extent of the scotland polygon

### PR DESCRIPTION
**Pull request by gravitystorm**
It previously extended too far north and included the Faroe Islands.

I haven't recalculated the area, but the contributing guide suggests this will be calculated automatically.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks!  
* Yes `area` will be calculated automatically on build...
* I'm working on #291 right now which will let us depend on a new library called [country-coder](https://github.com/ideditor/country-coder) .. 
(hat tip to @quincylvania  🎩) 
* I took a look at their [data](https://github.com/ideditor/country-coder/blob/master/src/data/borders.json), and it seems like they already have the Scottish boundary not including the Faroe Islands
* So I'm going to close this since it will be fixed in a few days anyway, and there's no point in generating a merge conflict in a file that will be going away 😆

**Comment by gravitystorm** [comment]
>     * So I'm going to close this since it will be fixed in a few days anyway, and there's no point in generating a merge conflict in a file that will be going away

Fair enough!

**Comment by bhousel** [comment]
ok haha..  Funny story..
It turns out Scotland doesn't have their own ISO country code, so we do need this .geojson file to stay around after all because sub-country regions are not supported in country-coder yet.  So I'll be taking this PR after all haha.

**Comment by bhousel** [comment]
Since you deleted the branch, I'm just going to do the same thing over on my branch  😆

**Comment by gravitystorm** [comment]
> Since you deleted the branch, I'm just going to do the same thing over on my branch laughing

Sorry for the hassle! The boundary in your branch looks good to me.

**Pull request closed without merging**
