### PR TITLE
Create be-maptime.json (Maptime Belgium)

### PR DESCRIPTION
**Pull request by jbelien**

### CODE REVIEW

**Comment by bhousel** [comment]
Oh @jbelien, I merged this, but looking at it a bit closer isn't this kind of the same as the meetup?

**Comment by bhousel** [comment]
We can keep them both there, but I've seen other Maptime chapters just link to their Meetup page, since that's where all the fun is.

**Comment by jbelien** [comment]
Actually, we (try to) use all of it.
I think the Facebook page is not used a lot (but I'm not on Facebook myself, so not the best judge here).
And the IRC is just a bridge to the Matrix channel.

Maybe @joostschouppe @marcgemis @xivk can help "clean" it a bit :)

**Comment by joostschouppe** [comment]
Facebook and Forum are low volume, but we kind of want to offer a medium for everyone
Mailing list is still our main "official" channel
Maptime is "just" for calendar, but is nice for people who prefer to use github to follow rather than meetup
Matrix is our core channel these days
And Twitter is Twitter
IRC as above is not really needed; I'm poking the matrix people to ask if it might go

**Comment by gplv2** [comment]
Why is having 'a lot' of ways to reach us a bad thing ?  Wasn't the idea to assemble ALL different channels to reach us together next to each other.   If this is a problem on the presentation end, maybe you could filter out some channels , but deleting them from the repository does sound a bit contra-productive imho.

**Comment by M1dgard** [comment]
IRC is bridged to Matrix, so it's the same conversation you're accessing. I know this might not fit in the current model, but idealiter they could be shown as the same "conversation" with different ways to access it. Something that could be shown in data users such as iD like:

screenshot_2018-05-09_16-12-40

**Comment by gplv2** [comment]
I assume the problem is that the list is too long for iD to show nicely, I get that.  a json config option with the option to hide/show this in ID would be a solution too, I see this index being used elsewhere too, it's going to grow beyond just being used in iD imho.

**Comment by M1dgard** [comment]
> Maybe being able to sort the channels (see #114) could also fix this problem.
The most important channels would be displayed first no matter the number of resources.

Defining a threshold below which stuff is shown in a "More" section could also be useful.

**Comment by joostschouppe** [comment]
@gplv2 [seems unlikely](https://josm.openstreetmap.de/ticket/16226) when it comes to the logical next victim JOSM, but it's almost a stand-alone website already thanks to @jbelien

**Comment by bhousel** [comment]
> I assume the problem is that the list is too long for iD to show nicely, I get that. 

I think my concern is more about overwhelming new users with [too many options](https://en.wikipedia.org/wiki/Overchoice) to explore.  I mostly just want them to get the idea that OSM is a friendly place for everyone, not just tech geeks.  We can improve this in the iD UI by filtering or rotating the sources if there are too many.

> a json config option with the option to hide/show this in ID would be a solution, I see this index being used elsewhere too, it's going to grow beyond just being used in iD imho.

Oh yeah definitely - I'd love to see it used more places than iD.  So that's a good reason to add more stuff to it, and move the information management issues to iD.

**Pull request merged**
