### PR TITLE
Adding Serbian community resources

### PR DESCRIPTION
**Pull request by stalker314314**
Initial addition of all things I can collect about Serbian projects. Note that we keep programming resources under Gitlab, and I added them under "github" type (since there were no "gitlab" type and I though that generic "osm" type will not do the justice).

### CODE REVIEW

**Comment by bhousel** [comment]
> since there were no "gitlab" type and I though that generic "osm" type will not do the justice

We could add a gitlab type - FontAwesome supports it:  https://fontawesome.com/icons?d=gallery&q=gitlab&s=brands

**Comment by stalker314314** [comment]
Or maybe you could broaden definition of "github" type. Rename it to "git" (everything related to git, including github, gitlab etc.) with git icon (because git != github :D). Or, if you don't want to stop with git, rename it to "sources", such that it represent collection of source codes for a given community (but, I cannot find appropriate FontAwesome icon for it).

(I am just throwing ideas, any approach is fine by me!)

**Comment by bhousel** [comment]
The purpose of the `type` is to match it to a reasonable icon, so I'll just add a `gitlab` one.

I don't think things like `github` and `gitlab` are really the kinds of "communities" that you want to push onto people who are just casuallly editing around Serbia, but if you want to do that we support it.

**Comment by stalker314314** [comment]
No, didn't want to push anything to people (especially explaining them why github != git) :smile: . But, I guess approach with "gitlab" type (as you did it) makes sense (otherwise osm-community-index wouldn't have matrix, telegram, irc... as types, you would have only one named "messaging" :smile: ). At least this is how I rationalized it to myself:) Anyway, thanks for very quick response and addition!

**Comment by jbelien** [comment]
GitLab resources have been added to https://community.osm.be/ 🎉

**Pull request merged**
