### PR TITLE
Npm build command

### PR DESCRIPTION
**Pull request by jnicho02**
Found this when setting up a new dev environment. The npm install needs to reference the dev dependencies

### CODE REVIEW

**Comment by bhousel** [comment]
That's odd.. It should work the same whether `--only=dev` is there or not.
This project only has dev dependencies.

Did you get an error without the option present?

**Comment by jnicho02** [comment]
Yes, errored on colors not being installed. Node 10 Mac OS X nvm.

**Comment by bhousel** [comment]
Hmm... is your `$NODE_ENV` environment variable set to `production` ?
That's the only reason that I would think that `npm install` would skip installing the dev dependencies.  It normally installs them.

You can check this with a command like:
`echo $NODE_ENV`

(It should probably return nothing / not be set)

**Comment by jnicho02** [comment]
Screenshot 2019-10-01 at 8 23 50 am
my $NODE_ENV is blank.

It's not a biggy, so happy if you close the issue if you are sure. My node experience is not extensive. Perhaps it is the npm version that matters?

**Comment by bhousel** [comment]
> It's not a biggy, so happy if you close the issue if you are sure.

Ok, yeah I'm going to close this, but I'll keep it in the back of my mind.  `npm install` really should install all of the dependencies you need to work with the code..

**Pull request closed without merging**
