### PR TITLE
community links for France

### PR DESCRIPTION
**Pull request by cquest**
Not sure it matches exactly was is expected... especially regarding translations...

### CODE REVIEW

**Comment by bhousel** [comment]
> Not sure it matches exactly was is expected... especially regarding translations...

Oh yeah - can you switch the texts to English?

**Comment by bhousel** [comment]
Thanks @cquest 👍

**Comment by cquest** [comment]
What's the (best) way to handle translations to have french contributors reading french link descriptions ?

**Comment by bhousel** [comment]
@cquest The strings will show up on Transifex:  https://www.transifex.com/openstreetmap/id-editor/community/

**Pull request merged**
